name: Log Extensions CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  # Run every Monday at 9AM PST (16 UTC)
  - cron: '0 16 * * 1'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm ci
        npx lerna bootstrap
    - name: Run Linting
      run: npm run lint
    - name: Inspect Lockfile
      run: npm run lint:lockfile

  types:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm ci
        npx lerna bootstrap
    - name: Run Type Checking (TSD)
      run: |
        cd packages/winston-log-enricher
        npm run types

  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm ci
        npx lerna bootstrap
    - name: Run Unit Tests
      run: npm run unit
    - name: Post Unit Test Coverage
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/unit
        token: ${{ secrets.CODECOV_TOKEN }}
        files: lcov.info
        flags: unit-tests-${{ matrix.node-version }}

  versioned:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm ci
        npx lerna bootstrap
    - name: Run Versioned Tests
      run: npm run versioned
    - name: Post Versioned Test Coverage
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/versioned
        token: ${{ secrets.CODECOV_TOKEN }}
        files: lcov.info
        flags: versioned-tests-${{ matrix.node-version }}
